# Geekish.Fun
markdown: kramdown

# URL of the Site
url: #'www.geekish.fun'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Geekish.Fun
# Description of the Site
description: Welcome to the Geekish.Fun
headerdescription: Hi, I'm Ehsan!
# URL of Image of the Site
site-image: /assets/images/meta.png
# Keywords of the Site
site-keywords: Geek, Geekish,Fun,C#,Data,AI,coding,blog
# URL for the Image of custom Favicon
favicon-url: /assets/images/logo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
#heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: https://images.pexels.com/photos/135018/pexels-photo-135018.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ed.man6ri@gmail.com
facebook_username: /
twitter_username: /
instagram_username:
linkedin_username: ehsan-manouchehri-79a6859b
github_username:  E4M9i
youtube_channel_id: / #UCk_93NXYP-U_AOB5GfWlOow
reddit_username: 
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Ehsan

# Name of the Author
author-name: Ehsan Manouchehri
# tiltle of the Author
author-title: Software Architect
# URL for the Image of the Author
author-image: /assets/images/ehsan02.jpg #https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: I'm an experienced software architect with over 17 years of expertise in the field. Throughout my career, I have specialized in modern architecture patterns, including Distributed Systems, Domain-Driven Design, and Event-Driven architectures. With a passion for simplifying complex concepts, I strive to make technology more accessible and understandable for everyone. In recent years, I have directed my focus towards cloud-native architecture and Complex Event/Stream Processing Platforms. This shift has allowed me to stay at the forefront of emerging trends and technologies in the industry.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.linkedin.com/in/ehsan-manouchehri-79a6859b/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
